apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kafka.yaml
  - kafka-prometheus.yaml
  - kafka-podmonitor.yaml
  - kafka-prometheusrule.yaml
  - kafka-dashboard.yaml
