# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: demo-external-user
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:

  template:
    secret:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: "demo-external"

  authentication:
    type: tls
  authorization:
    type: simple

    # Example ACL rules for Knative Brokers for Apache Kafka in the `demo-external` namespace.
    acls:
      - resource:
          type: topic
          name: "demo-external-topic"
          patternType: literal
        operations:
          - Write
          - Describe
          - DescribeConfigs
          - Read
        host: "*"

      - resource:
          type: group
          name: "knative-trigger-demo-external-*"
          patternType: literal
        operations:
          - Describe
          - Delete
          - Read
        host: "*"
