apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-cop/gitops-catalog/serverless-operator/operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-serving/overlays/default?ref=main
  - github.com/redhat-cop/gitops-catalog/amq-streams-operator/operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/elasticsearch-operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/jaeger-operator/overlays/stable?ref=main
  - github.com/pierDipi/gitops-catalog/red-hat-camel-k/operator/overlays/1.10.x?ref=add-camel-k
  - jaeger/
  - knative-eventing/
  - kafka/
  - kafka-secrets-transformer/

