apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: ui-source
  labels:
    app: ui
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: ui
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker