image:
  repository: quay.io/mittwald/kubernetes-replicator
  #tag: stable # if no tag is given, the chart's appVersion is used
  pullPolicy: Always
imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""
grantClusterAdmin: false
automountServiceAccountToken: true
args: [ ]
# - -resync-period=30m
# - -allow-all=false

## Deployment strategy / DaemonSet updateStrategy
##
updateStrategy: { }
#   type: RollingUpdate
#   rollingUpdate:
#     maxUnavailable: 1

serviceAccount:
  create: true
  annotations: { }
  name:
  privileges: [ ]
  automountServiceAccountToken: true

podSecurityContext: {}

securityContext:
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

priorityClassName: ""

resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

podLabels: { }

podAnnotations: { }

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1