apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - subscription.yaml
  - registry.yaml
  - registry-kafkauser.yaml
  - strimzi-secret-transformer.yaml

