apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: apicurio-registry-user
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - operation: All
        resource:
          name: 'kafkasql-journal'
          patternType: literal
          type: topic
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: cluster
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple