apiVersion: v1
kind: ServiceAccount
metadata:
  name: apicurio-registry-user-transformer
  namespace: kafka
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-user-transformer
  namespace: kafka
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ "apicurio-registry-user", "my-cluster-cluster-ca-cert" ]
    verbs: [ "get", "list", "watch" ]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-user-transformer
  namespace: apicurio-registry
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ "kafka-broker-secret" ]
    verbs: [ "create", "delete", "update", "patch", "get", "list", "watch" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-user-transformer
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apicurio-registry-user-transformer
subjects:
  - kind: ServiceAccount
    name: apicurio-registry-user-transformer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-user-transformer
  namespace: apicurio-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apicurio-registry-user-transformer
subjects:
  - kind: ServiceAccount
    name: apicurio-registry-user-transformer
    namespace: kafka
---
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: apicurio-registry-user-transformer
  namespace: kafka
spec:
  serviceAccountName: apicurio-registry-user-transformer
  prune: true
  interval: 5m
  matrix:
    - name: user_secret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: apicurio-registry-user
          namespace: kafka
    - name: cluster_ca_secret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: my-cluster-cluster-ca-cert
          namespace: kafka
  templates:
    - object:
        apiVersion: v1
        kind: Secret
        metadata:
          name: "kafka-broker-secret"
          namespace: "apicurio-registry"
        data:
          ca.p12: "{{ matrix.cluster_ca_secret.data['ca.p12'] }}"
          ca.password: "{{ matrix.cluster_ca_secret.data['ca.password'] }}"
          user.p12: "{{ matrix.user_secret.data['user.p12'] }}"
          user.password: "{{ matrix.user_secret.data['user.password'] }}"
