apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - service-account.yaml

secretGenerator:
  - name: app-config
    files:
      - app-config.production.yaml
      - secrets/AUTH_ORG_PRIVATE_KEY
    envs:
      - secrets/.env
    options:
      disableNameSuffixHash: true