apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventmesh-backend-user-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventmesh-backend-user-cluster-role
rules:
  # permissions for eventtypes, brokers and triggers
  - apiGroups:
      - "eventing.knative.dev"
    resources:
      - brokers
      - eventtypes
      - triggers
    verbs:
      - get
      - list
      - watch
  # permissions to get subscribers for triggers
  # as subscribers can be any resource, we need to give access to all resources
  # we fetch subscribers one by one, we only need `get` verb
  - apiGroups:
      - ""
      - "serving.knative.dev"
    resources:
      - "services"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventmesh-backend-user-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: eventmesh-backend-user-service-account
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: eventmesh-backend-user-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: eventmesh-backend-user-secret
  annotations:
    kubernetes.io/service-account.name: eventmesh-backend-user-service-account
type: kubernetes.io/service-account-token
